// <auto-generated />
using AgroSpace.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AgroSpace.Api.Migrations
{
    [DbContext(typeof(AgroDbContext))]
    [Migration("20260607224804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroSpace.Api.Models.Local", b =>
                {
                    b.Property<int>("IdLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_local");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocal"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("cidade");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("estado");

                    b.Property<int>("IdBioma")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_bioma");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nome");

                    b.HasKey("IdLocal");

                    b.ToTable("Locais");
                });

            modelBuilder.Entity("AgroSpace.Api.Models.Sensor", b =>
                {
                    b.Property<int>("IdSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_sensor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSensor"));

                    b.Property<int>("IdLocal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_local");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("status");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("tipo_sensor");

                    b.HasKey("IdSensor");

                    b.HasIndex("IdLocal");

                    b.ToTable("Sensor");
                });

            modelBuilder.Entity("AgroSpace.Api.Models.Sensor", b =>
                {
                    b.HasOne("AgroSpace.Api.Models.Local", "Local")
                        .WithMany("Sensores")
                        .HasForeignKey("IdLocal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");
                });

            modelBuilder.Entity("AgroSpace.Api.Models.Local", b =>
                {
                    b.Navigation("Sensores");
                });
#pragma warning restore 612, 618
        }
    }
}
